#docker-compose.yml
version: "3.8"

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  scraper:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/src
    environment:
      DB_URL: ${DB_URL}
