# docker-compose.yml - version satırını kaldırın
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  scraper:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      DB_URL: ${DB_URL}
      LOG_LEVEL: ${LOG_LEVEL}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
    ports:
      - "8000:8000"  # API portu için

volumes:
  postgres_data:
